# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

resources:
  pipelines:
  - pipeline: firstPipe # Name of the pipeline resource.
    source: ArnoldasMazeikaEpam.testDevOps.First # The name of the pipeline referenced by this pipeline resource.
    # project: FabrikamProject # Required only if the source pipeline is in another project
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes


pool: 
  name: Self agent test
  # demands:
  #   - agent -equals 1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'e43bfa47-9507-4275-8d37-97891357f4b5'
    pipeline: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'dateFromBuild'
    downloadPath: '$(System.ArtifactsDirectory)'
    cleanDestinationFolder: true
    
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      ls -la $(System.ArtifactsDirectory)/dateFromBuild
      tar -xvf $(System.ArtifactsDirectory)/dateFromBuild/dateFromBuild.tar 
      pwd
      ls -la